### ISSUE TITLE
Can not register a new user (url=/register, method=POST Error: Forbidden)

### ISSUE THREAD

**Issue by ARyaskov** [overleaf/web#65]
Hi!
I've run sharelatex on my VDS and got this error in log while trying to register a new user via web interface (after pressing on Register button):

```
[2014-04-21T22:52:04.439Z] ERROR: web-sharelatex/62053 on spring: error passed to top level next middlewear (url=/register, method=POST)
    Error: Forbidden
        at Object.exports.error (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
        at /home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
        at Object.handle (/home/latex/sharelatex/web/app/js/infrastructure/Server.js:97:14)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.handle (/home/latex/sharelatex/web/app/js/infrastructure/Server.js:87:14)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.session [as handle] (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.cookieParser [as handle] (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at multipart (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
        at /home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
        at IncomingMessage.<anonymous> (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
        at IncomingMessage.EventEmitter.emit (events.js:92:17)
        at _stream_readable.js:920:16
        at process._tickCallback (node.js:415:13)
```

Same thing happens with Login page/button.

```
[2014-04-21T22:58:47.155Z] ERROR: web-sharelatex/62053 on spring: error passed to top level next middlewear (url=/login, method=POST)
    Error: Forbidden
        at Object.exports.error (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
        at /home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
        at Object.handle (/home/latex/sharelatex/web/app/js/infrastructure/Server.js:97:14)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.handle (/home/latex/sharelatex/web/app/js/infrastructure/Server.js:87:14)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.session [as handle] (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.cookieParser [as handle] (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
        at next (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at multipart (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
        at /home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
        at IncomingMessage.<anonymous> (/home/latex/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
        at IncomingMessage.EventEmitter.emit (events.js:92:17)
        at _stream_readable.js:920:16
        at process._tickCallback (node.js:415:13)

```

Configuration:
FreeBSD10 x64
NodeJS v0.10.26
MongoDB 2.4.10
Redis 2.9.51
## 

Best regards, Andrew

**Comment by maycel8607** [comment]
Hello audax 
 
where I can do the set up you stated above?

**Comment by audax** [comment]
That is part of an nginx config.
