### ISSUE TITLE
MongoDB 2.6.12 duplicate null readAndWrite token prevents creation of new projects

### ISSUE THREAD

**Issue by dmyates** [overleaf/web#688]
##  Steps to Reproduce

1. Run Overleaf docker container with Mongodb 2.6.12 and set up users as normal.
2. Create a project.
3. Create a second project. This will fail.
4. Open the first project and turn on link sharing.
5. Create a second project. This will now succeed.

## Expected Behaviour

It should be possible to create new projects without turning on link sharing for all existing projects.

## Observed Behaviour

Link sharing must be enabled for all projects on the instance before it is possible to successfully create a new project.

## Technical Info

From `/var/log/sharelatex/web.log`

```
{
  "name": "web",
  "hostname": "356f010189e2",
  "pid": 150,
  "level": 50,
  "err": {
    "message": "insertDocument :: caused by :: 11000 E11000 duplicate key error index: sharelatex.projects.$tokens.readAndWrite_1  dup key: { : null }",
    "name": "MongoError",
    "stack": "WriteError({\"code\":11000,\"index\":0,\"errmsg\":\"insertDocument :: caused by :: 11000 E11000 duplicate key error index: sharelatex.projects.$tokens.readAndWrite_1  dup key: { : null }\",\"op\":{\"owner_ref\":\"5db14f9a033a550092b1e74a\",\"_id\":\"5db15fa66c89ef0096ef068b\",\"collabratecUsers\":[],\"tokenAccessReadAndWrite_refs\":[],\"tokenAccessReadOnly_refs\":[],\"deletedFiles\":[],\"deletedDocs\":[],\"trashed\":[],\"description\":\"\",\"deletedByExternalDataSource\":false,\"spellCheckLanguage\":\"en\",\"compiler\":\"pdflatex\",\"publicAccesLevel\":\"private\",\"rootFolder\":[{\"_id\":\"5db15fa66c89ef0096ef068a\",\"folders\":[],\"fileRefs\":[],\"docs\":[],\"name\":\"rootFolder\"}],\"readOnly_refs\":[],\"collaberator_refs\":[],\"active\":true,\"lastUpdated\":\"2019-10-24T08:24:06.060Z\",\"name\":\"dasfs\",\"__v\":0}})\n    at Function.MongoError.create (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:139:22)\n    at /var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/collection.js:669:23\n    at handleCallback (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)\n    at /var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:465:9\n    at handleCallback (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)\n    at resultHandler (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:413:5)\n    at /var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n",
    "info": {},
    "code": 11000
  },
  "url": "/project/new",
  "method": "POST",
  "user": {
    "id": "5db14f9a033a550092b1e74a",
    "email": "admin@example.com"
  },
  "msg": "error passed to top level next middleware",
  "time": "2019-10-24T08:24:06.076Z",
  "v": 0
}
```

## Analysis

As far as I can tell, the problem is that Mongo expects the `sharelatex.projects.$tokens.readAndWrite_1` key to be unique across projects, but this key is null for all projects with link sharing disabled. So new project creation fails if there's an existing project with link sharing disabled, because the null value for this key won't be unique.

I haven't tested if this issue is present in other versions of Mongodb.

**Comment by ShaneKilkelly** [comment]
Hi! thanks for bringing this to our attention.

I think this issue is caused by using Mongo 2.6, whereas we use a `partilaFilterExpression` on that index, which is only available in version 3 onwards: https://docs.mongodb.com/manual/core/index-partial/

We recommend upgrading to the latest available version of Mongo 3.
